apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: 863404411791.dkr.ecr.us-west-2.amazonaws.com/jenkins-maven-docker:v<TAG>
        ports:
        - containerPort: 8080
